name: "Tests"

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
          - '1.10'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      julia-version: "${{ matrix.version }}"
      julia-arch: "${{ matrix.arch }}"
      os: "${{ matrix.os }}"
    secrets: "inherit"
